---
abstract: 'Create wiki pages from groups of phenotype info'
author:
  - 'Christopher Bottoms <molecules <at> cpan <dot> org>'
build_requires:
  Data::Section: 0
  File::Slurp: 0
  Test::LongString: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Neuffer-RenderPhenoGroupWikiPage
requires:
  Getopt::Long::Descriptive: 0
  LWP::Simple: 0
  autodie: 2.0
version: 0.0038
